# Generated by Django 6.0.3 on 2026-04-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_professional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='recommendation',
            field=models.CharField(max_length=120),
        ),
    ]
