# Generated by Django 6.0.3 on 2026-04-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_add_company_and_industry'),
        ('guide', '0003_alter_decision_recommendation'),
    ]

    operations = [
    ]
