# Generated by Django 6.0.3 on 2026-04-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_merge_20260409_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
