# Generated by Django 6.0.4 on 2026-04-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_industry_subscriptionplan_remove_decision_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
