# Generated by Django 6.0.3 on 2026-04-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_alter_userprofile_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('focus', models.TextField(blank=True)),
                ('modules', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('approach', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='field_key',
            field=models.CharField(blank=True, help_text='Internal field name (priority, complexity, etc.)', max_length=50),
        ),
        migrations.CreateModel(
            name='DecisionThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score_advantage', models.IntegerField(default=4, help_text='Minimum score difference needed to recommend this system (e.g., Odoo must lead by 4 points)')),
                ('is_fallback', models.BooleanField(default=False, help_text='Use this system as fallback when scores are close (e.g., Hybrid Strategy)')),
                ('erp_system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guide.erpsystem')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('question', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1, help_text='Weight/score for this option towards this system')),
                ('is_active', models.BooleanField(default=True)),
                ('erp_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.erpsystem')),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.questionoption')),
            ],
            options={
                'unique_together': {('question_option', 'erp_system')},
            },
        ),
    ]
